http:
  port: 8000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  admin:
    host: localhost
    paths: [ '/admin', '/admin/*', 'admin/login' ]
  user:
    host: localhost
    paths: [ '/user', '/user/*', '/user/login' ]
  room:
    host: localhost
    paths: [ '/room', '/room/*' ]
  message:
    host: localhost
    paths: [ '/message', '/message/*' ]
  participant:
    host: localhost
    paths: [ '/participant', '/participant/*', '/participant/roomId/*', '/participant/userId/*' ]
  crew:
    host: localhost
    paths: [ '/crew', '/crew/*', '/crew/name/search' ]
  movie:
    host: localhost
    paths: [ '/movie', '/movie/*' ]
  rating:
    host: localhost
    paths: [ '/rating', '/rating/*', '/rating/movie/*' ]
  review:
    host: localhost
    paths: [ '/review', '/review/*', '/review/movie/*' ]
  moview_crew:
    host: localhost
    paths: [ '/movie_crew', '/movie_crew/*', '/movie_crew/crewId/*' ]
serviceEndpoints:
  adminService:
    url: 'http://localhost:5000'
  userService:
    url: 'http://localhost:3000'
  roomService:
    url: 'http://localhost:5001'
  messageService:
    url: 'http://localhost:5002'
  participantService:
    url: 'http://localhost:5003'
  crewService:
    url: 'http://localhost:5004'
  movieService:
    url: 'http://localhost:3003'
  ratingService:
    url: 'http://localhost:3001'
  reviewService:
    url: 'http://localhost:3002'
  movieCrewService:
    url: 'http://localhost:3004'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  adminPipeline:
    apiEndpoints:
      - admin
    policies:
      - proxy:
          - action:
              serviceEndpoint: adminService
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  roomPipeline:
    apiEndpoints:
      - room
    policies:
      - proxy:
          - action:
              serviceEndpoint: roomService
              changeOrigin: true
  messagePipeline:
    apiEndpoints:
      - message
    policies:
      - proxy:
          - action:
              serviceEndpoint: messageService
              changeOrigin: true
  participantPipeline:
    apiEndpoints:
      - participant
    policies:
      - proxy:
          - action:
              serviceEndpoint: participantService
              changeOrigin: true
  crewPipeline:
    apiEndpoints:
      - crew
    policies:
      - proxy:
          - action:
              serviceEndpoint: crewService
              changeOrigin: true
  moviePipeline:
    apiEndpoints:
      - movie
    policies:
      - proxy:
          - action:
              serviceEndpoint: movieService
              changeOrigin: true
  ratingPipeline:
    apiEndpoints:
      - rating
    policies:
      - proxy:
          - action:
              serviceEndpoint: ratingService
              changeOrigin: true
  reviewPipeline:
    apiEndpoints:
      - review
    policies:
      - proxy:
          - action:
              serviceEndpoint: reviewService
              changeOrigin: true
  movieCrewPipeline:
    apiEndpoints:
      - moview_crew
    policies:
      - proxy:
          - action:
              serviceEndpoint: movieCrewService
              changeOrigin: true