# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - movie-club2(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - main
      
env:
  working-directory: ./server
  
jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - run: npm install
      working-directory: ./server/gateway/mcdb_gateway
    - run: npm install
      working-directory: ${{env.working-directory}}
    - run: npm test
      working-directory: ${{env.working-directory}}

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: movie-club2
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8762DCC57C66452FBE14CB64F704D626 }}
        package: .

