# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - movie-club(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - main

env:
  working-directory: ./server
  NODE_VERSION: '14.x'
  AZURE_WEBAPP_NAME: movie-club
  AZURE_WEBAPP_PACKAGE_PATH: ./client

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@main
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm install
      working-directory: ./server/gateway/mcdb_gateway
    - run: npm install
      working-directory: ${{env.working-directory}}
    - run: npm test
      working-directory: ${{env.working-directory}}

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_87DD4641FC814F309C0BE4389781C01A }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
