# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./server

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ${{env.working-directory}}
    - run: npm install
      working-directory: ${{env.working-directory}}
    - run: npm install
      working-directory: ./server/gateway/mcdb_gateway
    - run: npm test
      working-directory: ${{env.working-directory}}
    - run: npm run coverage
      working-directory: ${{env.working-directory}}
      env:
        CI: true
        
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: ../server/coverage/
